version: "2"
run:
  go: '1.25.5'

linters:
  settings:
    errcheck:
      exclude-functions:
        - "(*database/sql.Rows).Close"
        - "(*database/sql.DB).Close"
        - "(*database/sql.Conn).Close"
        - "(*sqlite.connection).Close"
  exclusions:
    rules:
      - linters:
          - errcheck
        path: 'cmd/stoat/main\.go'
        text: 'conn\.Close'
      - linters:
          - errcheck
        path: 'internal/ui/model/msgs\.go'
        text: 'f\.Close'
      - linters:
          - errcheck
        path: 'internal/ui/model/edit\.go'
        text: 'f\.Close'
      - linters:
          - errcheck
        path: 'internal/ui/model/query\.go'
        text: 'f\.Close'
