name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 1.26.2
      - uses: golangci/golangci-lint-action@v7
        with:
          version: v2.10.1
      - name: Run govulncheck
        run: make vuln-check
      - name: Run Tests
        run: make test
      - name: Run Build
        run: make build
      - name: Run Integration Tests
        run: make test-integration
